var Arr_Menu = [
    ["市场管理", "<h5 class=text-danger><span class='glyphicon glyphicon-list-alt'></span> 订单处理</h5><a href=/OMS/?Do=All>全部订单</a><a href=/OMS/?Do=UnConfirmed>待处理</a><a href=/OMS/?Do=Distribution>已配货</a><a href=/OMS/?Do=Post>已交运</a><a href=/OMS/?Do=UnShip>待发货</a><a href=/OMS/?Do=Ship>已派送</a><br/><a href=/OMS/?Do=CancelOrder>已取消</a><a href=/OMS/?Do=OutOfStock><font color=red>缺货</font></a><h5 class=text-danger><span class='glyphicon glyphicon-envelope'></span> 客户服务</h5><a href=/OMS/Message.aspx?Do=UnExecute>待处理邮件</a><a href=/OMS/Message.aspx?Do=Ask>收件箱</a><a href=/OMS/Message.aspx?Do=Send>发件箱</a><a href=/OMS/Message.aspx?Do=Base>系统</a><a href=/OMS/Message.aspx?Do=Star>星标</a><a href=/OMS/Message.aspx?Do=Crash>紧急</a><h5 class=text-danger><span class='glyphicon glyphicon-credit-card'></span> 售后管理</h5><a href=/CustomerService/?Do=All>所有售后单</a><a href=/CustomerService/?Do=Doing>进行中</a><a href=/CustomerService/?Do=Complete>已结束</a><a href=/CustomerService/?Do=Cancel>已取消</a><h5 class=text-danger><span class='glyphicon glyphicon-wrench'></span> 工具</h5><a href=/OMS/Product.aspx>商品管理</a><a href='/Product/FullSku.aspx'>产品中心</a>", "<br/>"],
    ["产品管理", "<h5 class=text-danger><span class='glyphicon glyphicon-list-alt'></span> 产品管理</h5><a href='/Product/?Do=All'>全部产品</a><a href='/Product/?Do=Sold'>在售产品</a><a href='/Product/?Do=Clearance'>清仓产品</a><a href='/Product/?Do=End'>下架产品</a><a href='/Product/Operate.aspx'>产品运营</a><h5 class=text-danger><span class='glyphicon glyphicon-wrench'></span> 设置</h5><a href='/Product/TAG.aspx'>产品类别</a>", "<br/>"],
	["采购", "<h5 class=text-danger><span class='glyphicon glyphicon-list-alt'></span> 采购单</h5><a href='/Purchase/?Do=UnExecute'>待采购</a><a href='/Purchase/?Do=NoPaid'>待付款</a><a href='/Purchase/?Do=UnStock'>待收货</a><a href='/Purchase/?Do=Complete'>已完成</a><a href='/Purchase/?Do=Cancel'>已取消</a><h5 class=text-danger><span class='glyphicon glyphicon-wrench'></span> 工具</h5><a href='/Purchase/Supplier.aspx'>供应商管理</a>", "<br/>"],
	["仓储管理", "<h5 class=text-danger><span class='glyphicon glyphicon-send'></span> 运单</h5><a href=/Logistics/?Do=AllShip>全部运单</a><a href=/Logistics/?Do=UnDistribution>待配货</a><a href=/Logistics/?Do=UnPost>待交运</a><a href=/Logistics/?Do=UnOutStock>待出库</a><a href=/Logistics/?Do=OutStock>已出库</a><a href=/Logistics/?Do=CutOff>截单</a><a href=/Logistics/?Do=Cancel>取消</a><a href=/Logistics/?Do=UnCost>待结算</a><a href=/Logistics/?Do=UnTracking>无挂号</a><h5 class=text-danger><span class='glyphicon glyphicon-plane'></span> 物流单 & 调拨单</h5><a href='/Logistics/InStore.aspx'>入库单</a><a href='/Logistics/RequisitionOrder.aspx?Do=UnVerify'>待审核</a><a href='/Logistics/RequisitionOrder.aspx?Do=UnDistribution'>待配货</a><a href='/Logistics/RequisitionOrder.aspx?Do=UnPost'>待出库</a><a href='/Logistics/RequisitionOrder.aspx?Do=Ongoing'>待入库</a><a href='/Logistics/RequisitionOrder.aspx?Do=UnCost'>待结算</a><h5 class=text-danger><span class='glyphicon glyphicon-list-alt'></span> 查询</h5><a href='/Logistics/Stock.aspx'>库存查询</a><h5 class=text-danger><span class='glyphicon glyphicon-th-large'></span> 操作</h5><a href='/Logistics/Order.aspx'>出库复核</a><a href='/Logistics/OutOfStock.aspx'>未出库复核</a><a href='/Logistics/Receive.aspx?Do=UnReceive'>收货单</a><a href='/Logistics/Product.aspx'>库存产品</a><h5 class=text-danger><span class='glyphicon glyphicon-wrench'></span> 物流配置</h5><a href='/Logistics/Warehouse.aspx'>仓库配置</a><a href='/Logistics/Freight.aspx'>货代配置</a><a href='/Logistics/Project.aspx'>物流方案</a>", "<br/>"],
	["财务", "<h5 class=text-danger><span class='glyphicon glyphicon-list-alt'></span> 请款单</h5><a href='/Finance/?Do=All'>全部</a><a href='/Finance/?Do=UnConfirmed'>待审核</a><a href='/Finance/?Do=UnPaid'>待支付</a><a href='/Finance/?Do=Complete'>已完成</a><a href='/Finance/?Do=Cancel'>已取消</a><h5 class=text-danger><span class='glyphicon glyphicon-random'></span> 售后请款单</h5><a href='/Finance/Refund.aspx?Do=All'>全部</a><a href='/Finance/Refund.aspx?Do=UnExecute'>待处理</a><a href='/Finance/Refund.aspx?Do=Complete'>已完成</a><a href='/Finance/Refund.aspx?Do=Cancel'>已取消</a><h5 class=text-danger><span class='glyphicon glyphicon-wrench'></span> 工具</h5><a href='/Finance/PayPal.aspx?Do=InCome'>PayPal流水</a><a href='/Finance/ExchangeRate.aspx'>汇率</a>", "<br/>"],
    ["运营管理", "<h5 class=text-danger><span class='glyphicon glyphicon-th-large'></span> 对接平台设置</h5><a href='/OMS/ShopeBay.aspx'>eBay店铺</a><a href='/OMS/BankPaypal.aspx'>Bank账号管理</a><h5 class=text-danger><span class='glyphicon glyphicon-wrench'></span> 工具</h5><a href='/Control/'>调度任务管理</a><a href='/Control/'>定时下架</a><h5 class=text-danger><span class='glyphicon glyphicon-eye-open'></span> 人员设置</h5><a href='/user/?Do=InService'>用户</a><a href='/user/team.aspx'>团队</a><a href='/user/role.aspx?Refresh=1'>角色</a><a href='/user/power.aspx?Refresh=1'>权限</a>",
        "<strong>提示：</strong>远程服务器已经关闭"]
];
